### PR TITLE
Load pages

### PR DESCRIPTION
**Pull request by piranna**
Enabled xcb for testing purposses, and now I've been able to load both a local `file://` html file and Google web page. I've found `file://` scheme require absolute paths, maybe that's the reason why it was not working before.

### CODE REVIEW

**Comment by mitsukaki** [comment]
:D amma jack this, build it, and play with it 'till I get bored.

**Comment by Coretool** [comment]
I could have told you that... URLs of webpages have to be in 'complete'  form too!

**Comment by piranna** [comment]
> :D amma jack this, build it, and play with it 'till I get bored.

Lol :-P

> I could have told you that... URLs of webpages have to be in 'complete' form too!

Didn't have time to figure it before, if not I could have been able to integrate it on my thesis, but now I don't have time :-( Anyway, we need to improve errors checking, by default it load `about:blank` and don't give any signal that anything went wrong... :-/

And the proves :-)
screenshot at 2016-05-08 23 24 07
screenshot at 2016-05-08 23 28 06

**Comment by Coretool** [comment]
Yeah, I have to take a look at the Webview errors !

**Comment by piranna** [comment]
:+1: I would check n first instance the `onLoaded()` event to check if the given URL is correct or not, and in that case close the app with a fatal error (similar to call it without an URL). Other thing we need is a way to close it, but maybe calling to `window.close()` from Javascript is just enough...

**Comment by Coretool** [comment]
Tasks added to my diary :+1:

**Comment by piranna** [comment]
:+1:

**Pull request merged**
